version: '3'
services: 
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
  backend:
    build: ./backend
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./backend:/go/src/backend