version: '3'
services: 
  frontend:
    container_name: mers-frontend
    build: ./frontend
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'yarn install && yarn start'
    ports:
      - '3000:3000'
    