version: '3'
services: 
  frontend:
    container_name: mers-frontend
    build: ./frontend
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'yarn install && yarn start'
  backend:
    container_name: api-server
    build: ./backend
    ports:
      - 3000:3000
    tty: true
