openapi: 3.0.0
info:
  title: MERS API
  version: 1.0.0
  license:
    name: MIT
servers:
- url: http://localhost:3000
paths:
  /recording-start:
    get:
      summary: Start recording Map1058
      operationId: get-recording-start
      tags:
        - recording-start
      responses:
          '200':
            description: successful to start recording Map1058
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /recording-pauset:
    get:
      summary: Pause recording Map1058
      operationId: get-recording-pause
      tags:
        - recording-pause
      responses:
          '200':
            description: successful to pause recording Map1058
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /images:
    get:
      summary: Randomly get Google Drive IDs for images
      operationId: get-image-ids
      tags:
        - images
      responses:
        '200':
          description: Successful to get image IDs
          content:
              application/json:    
                schema:
                  $ref: "#/components/schemas/ListImages"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /movies:
    get:
      summary: Randomly get Google Drive IDs for movies
      tags:
        - movies
      operationId: get-movie-ids
      responses:
        "200":
          description: Successful to get movie IDs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListMovies"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /trials:
    post:
      summary: create a trial result
      tags:
        - trials
      operationId: post-trials
      description: create a trial result containing a set of a subject info and rating results
      requestBody:
        description: trial result
        required: true
        $ref: '#/components/requestBodies/Trial'
      responses:
        '201':
          description: successful to create a trial result
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  requestBodies:
    Trial:
      content:
        application/json:
          schema:
            type: object
            properties:
              trial_metadata:
                type: object
                properties:
                  location:
                    type: string
                  platform:
                    type: string
                  pre_started_at:
                    type: string
                  started_at:
                    type: string
                  ended_at:
                    type: string
                  rating_second_by_media:
                    type: integer
                    format: uint64
                  number_of_medias:
                    type: integer
                    format: uint64
              subject_metadata:
                type: object
                properties:
                  id:
                    type: integer
                    format: uint64
                  age:
                    type: integer
                    format: uint64
                  gender:
                    type: string
                  handedness:
                    type: string
                  vision:
                    type: string
                  vision_aid:
                    type: string
                  education:
                    type: string
                  alcohol_consumption:
                    type: string
                  coffee_consumption:
                    type: string
                  tea_consumption:
                    type: string
                  tobacco_consumption:
                    type: string
                  drug_consumption:
                    type: string
                  syndroms:
                    type: string
                  hours_of_sleep_last_night:
                    type: number
                    format: float
                  normal_hours_of_sleep:
                    type: number
                    format: float
                  level_of_alertness:
                    type: string
                  head_circumference:
                    type: number
                    format: float
                  distance_nasion_inion:
                    type: number
                    format: float
                  distance_left_right_jaw_hinge:
                    type: number
                    format: float
              rating_set:
                type: object
                properties:
                  media_type:
                      type: string
                  rating:
                    type: array
                    items:
                      type: object
                      properties:
                        dataset:
                          type: string
                        filename:
                          type: string
                        emotion:
                          type: object
                          properties:
                            valence:
                              type: number
                              format: float
                            arousal:
                              type: number
                              format: float
                            liking:
                              type: number
                              format: float
                            dominance:
                              type: number
                              format: float
                            famility:
                              type: number
                              format: float
            required:
              - trial_metadata
              - subject_metadata
              - rating_set
  schemas:
    ListImages:
      type: array
      items:
        type: object
        properties:
          image_id:
            type: integer
            format: uint64
          google_drive_id:
            type: string
    ListMovies:
      type: array
      items:
        type: object
        properties:
          movie_id:
            type: integer
            format: uint64
          google_drive_id:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
      - code
      - message

