openapi: 3.0.0
info:
  license:
    name: MIT
  title: Swagger Petstore
  version: 1.0.0
servers:
- url: http://localhost:3000/v1
paths:
  /movies:
    get:
      summary: get a display movie
      tags:
      - movies
      operationId: getMovie
      parameters:
      - name: id
        in: path
        description: Movie ID
        required: true
        schema:
          type: integer
          format: uint32
      responses:
        "200":
          description: URL for Movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /targets:
    get:
      summary: get some rated targets
      tags:
      - targets
      operationId: getTargets
      parameters:
      - name: type
        in: path
        description: media type
        required: true
        schema:
          type: string
          example:
          - image
          - movie
      - name: num
        in: path
        description: how many rated targets to get
        required: true
        schema:
          type: integer
          format: uint32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Targets'
  /trials:
    post:
      summary: create a trial result
      description: create a trial result containing a set of a subject info and rating results      
      requestBody:
        description: trial result
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trial'
      responses:
        '201':
          description: successful to create a trial result

components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
          format: uint32
        url:
          type: string
      required:
        - id
        - url
    Targets:
      type: array
      items: 
        type: object
        properties:
          type: 
            type: string
          ids:
            type: array
            items:
              type: string
    Trial:
      type: object
      properties:
        datetime:
          type: string
          format: date-time
        subject:
          type: object
        ratings:
          type: array
          items:
            type: object
            properties:
              media_id:
                type: integer
              emotions:
                type: object
                properties:
                  valence:
                    type: number
                    format: float
                  arousal:
                    type: number
                    format: float
                  liking:
                    type: number
                    format: float
                  dominance:
                    type: number
                    format: float
                  famility:
                    type: number
                    format: float
              
      required:
        - date
        - subject
        - medias
        - emotions
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
