/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostTrialsRequestRatingSetRatingInnerEmotion struct {

	Valence float32 `json:"valence,omitempty"`

	Arousal float32 `json:"arousal,omitempty"`

	Liking float32 `json:"liking,omitempty"`

	Dominance float32 `json:"dominance,omitempty"`

	Famility float32 `json:"famility,omitempty"`
}

