/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostTrialsRequestTrialMetadata struct {

	ConditionId int32 `json:"condition_id,omitempty"`

	ChannelTypeId int32 `json:"channel_type_id,omitempty"`

	PreStartedAt string `json:"pre_started_at,omitempty"`

	StartedAt string `json:"started_at,omitempty"`

	EndedAt string `json:"ended_at,omitempty"`
}

