/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostTrialsRequestTrialMetadata struct {

	Location string `json:"location,omitempty"`

	Platform string `json:"platform,omitempty"`

	PreStartedAt string `json:"pre_started_at,omitempty"`

	StartedAt string `json:"started_at,omitempty"`

	EndedAt string `json:"ended_at,omitempty"`

	RatingSecondByMedia int32 `json:"rating_second_by_media,omitempty"`

	NumberOfMedias int32 `json:"number_of_medias,omitempty"`
}

