/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type ListImagesInner struct {

	ImageId int32 `json:"image_id,omitempty"`

	GoogleDriveId string `json:"google_drive_id,omitempty"`
}

