/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostTrialsRequestRatingSetRatingInner struct {

	Dataset string `json:"dataset,omitempty"`

	Filename string `json:"filename,omitempty"`

	Emotion PostTrialsRequestRatingSetRatingInnerEmotion `json:"emotion,omitempty"`
}

