/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostTrialsRequestRating struct {

	MediaType string `json:"media_type,omitempty"`

	Rate []PostTrialsRequestRatingRateInner `json:"rate,omitempty"`
}

