/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type ExprimentSettings struct {

	ExprimentConditions []ExprimentSettingsExprimentConditionsInner `json:"expriment-conditions,omitempty"`

	ChannelTypes []ExprimentSettingsChannelTypesInner `json:"channel-types,omitempty"`
}

