/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetExprimentSettings200Response struct {

	ExprimentConditions []GetExprimentSettings200ResponseExprimentConditionsInner `json:"expriment-conditions,omitempty"`

	ChannelTypes []GetExprimentSettings200ResponseChannelTypesInner `json:"channel-types,omitempty"`
}

