/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostTrialsRequestRatingRateInner struct {

	Filename string `json:"filename,omitempty"`

	Emotions PostTrialsRequestRatingRateInnerEmotions `json:"emotions,omitempty"`
}

