/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

import (
	"time"
)

type PostTrialsRequest struct {

	Location string `json:"location,omitempty"`

	Platform string `json:"platform,omitempty"`

	PreTrialStartedAt time.Time `json:"pre_trial_started_at"`

	TrialStartedAt time.Time `json:"trial_started_at"`

	TrialEndedAt time.Time `json:"trial_ended_at"`

	Subject PostTrialsRequestSubject `json:"subject"`

	Rating PostTrialsRequestRating `json:"rating"`
}

