/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type GetExprimentSettings200ResponseExprimentConditionsInner struct {

	ConditionId int32 `json:"condition_id,omitempty"`

	ConditionName string `json:"condition_name,omitempty"`

	Location string `json:"location,omitempty"`

	MediaType string `json:"media_type,omitempty"`

	NumberOfMedias int32 `json:"number_of_medias,omitempty"`

	RatingSecondByMedia int32 `json:"rating_second_by_media,omitempty"`

	Dataset string `json:"dataset,omitempty"`

	Platform string `json:"platform,omitempty"`
}

