/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema

type PostChannelTypesRequest struct {

	ChannelTypeName string `json:"channel_type_name,omitempty"`

	Channels []string `json:"channels,omitempty"`
}

