/* tslint:disable */
/* eslint-disable */
/**
 * MERS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ListImagesInner
 */
export interface ListImagesInner {
    /**
     * 
     * @type {number}
     * @memberof ListImagesInner
     */
    'image_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListImagesInner
     */
    'google_drive_id'?: string;
}
/**
 * 
 * @export
 * @interface ListMoviesInner
 */
export interface ListMoviesInner {
    /**
     * 
     * @type {number}
     * @memberof ListMoviesInner
     */
    'movie_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListMoviesInner
     */
    'google_drive_id'?: string;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {number}
     * @memberof ModelError
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface PostTrialsRequest
 */
export interface PostTrialsRequest {
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequest
     */
    'datetime'?: string;
    /**
     * 
     * @type {PostTrialsRequestSubject}
     * @memberof PostTrialsRequest
     */
    'subject': PostTrialsRequestSubject;
    /**
     * 
     * @type {Array<PostTrialsRequestRatingsInner>}
     * @memberof PostTrialsRequest
     */
    'ratings': Array<PostTrialsRequestRatingsInner>;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestRatingsInner
 */
export interface PostTrialsRequestRatingsInner {
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingsInner
     */
    'media_id'?: number;
    /**
     * 
     * @type {PostTrialsRequestRatingsInnerEmotions}
     * @memberof PostTrialsRequestRatingsInner
     */
    'emotions'?: PostTrialsRequestRatingsInnerEmotions;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestRatingsInnerEmotions
 */
export interface PostTrialsRequestRatingsInnerEmotions {
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingsInnerEmotions
     */
    'valence'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingsInnerEmotions
     */
    'arousal'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingsInnerEmotions
     */
    'liking'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingsInnerEmotions
     */
    'dominance'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingsInnerEmotions
     */
    'famility'?: number;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestSubject
 */
export interface PostTrialsRequestSubject {
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubject
     */
    'participant_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubject
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'handedness'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'vision'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'vision_aid'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'education'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'alcohol_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'coffee_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'tea_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'tobacco_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'drug_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'syndroms'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubject
     */
    'hours_of_sleep_last_night'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubject
     */
    'normal_hours_of_sleep'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubject
     */
    'level_of_alertness'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostTrialsRequestSubject
     */
    'distribute_physiological_recordings'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PostTrialsRequestSubject
     */
    'publish_audio_visual_recordings'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubject
     */
    'head_circumference'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubject
     */
    'distance_nasion_inion'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubject
     */
    'distance_left_right_jaw_hinge'?: number;
}

/**
 * ImagesApi - axios parameter creator
 * @export
 */
export const ImagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImageIds: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImagesApi - functional programming interface
 * @export
 */
export const ImagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getImageIds(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ListImagesInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getImageIds(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ImagesApi - factory interface
 * @export
 */
export const ImagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImagesApiFp(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImageIds(options?: any): AxiosPromise<Array<ListImagesInner>> {
            return localVarFp.getImageIds(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ImagesApi - object-oriented interface
 * @export
 * @class ImagesApi
 * @extends {BaseAPI}
 */
export class ImagesApi extends BaseAPI {
    /**
     * 
     * @summary Randomly get Google Drive IDs for images
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    public getImageIds(options?: AxiosRequestConfig) {
        return ImagesApiFp(this.configuration).getImageIds(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * MoviesApi - axios parameter creator
 * @export
 */
export const MoviesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for movies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMovieIds: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/movies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MoviesApi - functional programming interface
 * @export
 */
export const MoviesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MoviesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for movies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMovieIds(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ListMoviesInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMovieIds(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MoviesApi - factory interface
 * @export
 */
export const MoviesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MoviesApiFp(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for movies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMovieIds(options?: any): AxiosPromise<Array<ListMoviesInner>> {
            return localVarFp.getMovieIds(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MoviesApi - object-oriented interface
 * @export
 * @class MoviesApi
 * @extends {BaseAPI}
 */
export class MoviesApi extends BaseAPI {
    /**
     * 
     * @summary Randomly get Google Drive IDs for movies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoviesApi
     */
    public getMovieIds(options?: AxiosRequestConfig) {
        return MoviesApiFp(this.configuration).getMovieIds(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * TrialsApi - axios parameter creator
 * @export
 */
export const TrialsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * create a trial result containing a set of a subject info and rating results
         * @summary create a trial result
         * @param {PostTrialsRequest} [postTrialsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTrials: async (postTrialsRequest?: PostTrialsRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/trials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postTrialsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TrialsApi - functional programming interface
 * @export
 */
export const TrialsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TrialsApiAxiosParamCreator(configuration)
    return {
        /**
         * create a trial result containing a set of a subject info and rating results
         * @summary create a trial result
         * @param {PostTrialsRequest} [postTrialsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTrials(postTrialsRequest?: PostTrialsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postTrials(postTrialsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TrialsApi - factory interface
 * @export
 */
export const TrialsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TrialsApiFp(configuration)
    return {
        /**
         * create a trial result containing a set of a subject info and rating results
         * @summary create a trial result
         * @param {PostTrialsRequest} [postTrialsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTrials(postTrialsRequest?: PostTrialsRequest, options?: any): AxiosPromise<void> {
            return localVarFp.postTrials(postTrialsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TrialsApi - object-oriented interface
 * @export
 * @class TrialsApi
 * @extends {BaseAPI}
 */
export class TrialsApi extends BaseAPI {
    /**
     * create a trial result containing a set of a subject info and rating results
     * @summary create a trial result
     * @param {PostTrialsRequest} [postTrialsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrialsApi
     */
    public postTrials(postTrialsRequest?: PostTrialsRequest, options?: AxiosRequestConfig) {
        return TrialsApiFp(this.configuration).postTrials(postTrialsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


