/* tslint:disable */
/* eslint-disable */
/**
 * MERS API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ListImagesInner
 */
export interface ListImagesInner {
    /**
     * 
     * @type {number}
     * @memberof ListImagesInner
     */
    'image_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListImagesInner
     */
    'google_drive_id'?: string;
}
/**
 * 
 * @export
 * @interface ListMoviesInner
 */
export interface ListMoviesInner {
    /**
     * 
     * @type {number}
     * @memberof ListMoviesInner
     */
    'movie_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListMoviesInner
     */
    'google_drive_id'?: string;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {number}
     * @memberof ModelError
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface PostTrialsRequest
 */
export interface PostTrialsRequest {
    /**
     * 
     * @type {PostTrialsRequestTrialMetadata}
     * @memberof PostTrialsRequest
     */
    'trial_metadata': PostTrialsRequestTrialMetadata;
    /**
     * 
     * @type {PostTrialsRequestSubjectMetadata}
     * @memberof PostTrialsRequest
     */
    'subject_metadata': PostTrialsRequestSubjectMetadata;
    /**
     * 
     * @type {PostTrialsRequestRatingSet}
     * @memberof PostTrialsRequest
     */
    'rating_set': PostTrialsRequestRatingSet;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestRatingSet
 */
export interface PostTrialsRequestRatingSet {
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestRatingSet
     */
    'media_type'?: string;
    /**
     * 
     * @type {Array<PostTrialsRequestRatingSetRatingInner>}
     * @memberof PostTrialsRequestRatingSet
     */
    'rating'?: Array<PostTrialsRequestRatingSetRatingInner>;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestRatingSetRatingInner
 */
export interface PostTrialsRequestRatingSetRatingInner {
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestRatingSetRatingInner
     */
    'dataset'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestRatingSetRatingInner
     */
    'filename'?: string;
    /**
     * 
     * @type {PostTrialsRequestRatingSetRatingInnerEmotion}
     * @memberof PostTrialsRequestRatingSetRatingInner
     */
    'emotion'?: PostTrialsRequestRatingSetRatingInnerEmotion;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestRatingSetRatingInnerEmotion
 */
export interface PostTrialsRequestRatingSetRatingInnerEmotion {
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingSetRatingInnerEmotion
     */
    'valence'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingSetRatingInnerEmotion
     */
    'arousal'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingSetRatingInnerEmotion
     */
    'liking'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingSetRatingInnerEmotion
     */
    'dominance'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestRatingSetRatingInnerEmotion
     */
    'famility'?: number;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestSubjectMetadata
 */
export interface PostTrialsRequestSubjectMetadata {
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'age'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'handedness'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'vision'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'vision_aid'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'education'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'alcohol_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'coffee_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'tea_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'tobacco_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'drug_consumption'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'syndroms'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'hours_of_sleep_last_night'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'normal_hours_of_sleep'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'level_of_alertness'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'head_circumference'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'distance_nasion_inion'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestSubjectMetadata
     */
    'distance_left_right_jaw_hinge'?: number;
}
/**
 * 
 * @export
 * @interface PostTrialsRequestTrialMetadata
 */
export interface PostTrialsRequestTrialMetadata {
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestTrialMetadata
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestTrialMetadata
     */
    'platform'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestTrialMetadata
     */
    'pre_started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestTrialMetadata
     */
    'started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostTrialsRequestTrialMetadata
     */
    'ended_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestTrialMetadata
     */
    'rating_second_by_media'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostTrialsRequestTrialMetadata
     */
    'number_of_medias'?: number;
}

/**
 * ImagesApi - axios parameter creator
 * @export
 */
export const ImagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImageIds: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ImagesApi - functional programming interface
 * @export
 */
export const ImagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ImagesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getImageIds(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ListImagesInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getImageIds(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ImagesApi - factory interface
 * @export
 */
export const ImagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ImagesApiFp(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for images
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImageIds(options?: any): AxiosPromise<Array<ListImagesInner>> {
            return localVarFp.getImageIds(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ImagesApi - object-oriented interface
 * @export
 * @class ImagesApi
 * @extends {BaseAPI}
 */
export class ImagesApi extends BaseAPI {
    /**
     * 
     * @summary Randomly get Google Drive IDs for images
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ImagesApi
     */
    public getImageIds(options?: AxiosRequestConfig) {
        return ImagesApiFp(this.configuration).getImageIds(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * MoviesApi - axios parameter creator
 * @export
 */
export const MoviesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for movies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMovieIds: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/movies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MoviesApi - functional programming interface
 * @export
 */
export const MoviesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MoviesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for movies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMovieIds(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ListMoviesInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMovieIds(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MoviesApi - factory interface
 * @export
 */
export const MoviesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MoviesApiFp(configuration)
    return {
        /**
         * 
         * @summary Randomly get Google Drive IDs for movies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMovieIds(options?: any): AxiosPromise<Array<ListMoviesInner>> {
            return localVarFp.getMovieIds(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MoviesApi - object-oriented interface
 * @export
 * @class MoviesApi
 * @extends {BaseAPI}
 */
export class MoviesApi extends BaseAPI {
    /**
     * 
     * @summary Randomly get Google Drive IDs for movies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MoviesApi
     */
    public getMovieIds(options?: AxiosRequestConfig) {
        return MoviesApiFp(this.configuration).getMovieIds(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * RecordingPauseApi - axios parameter creator
 * @export
 */
export const RecordingPauseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Pause recording Map1058
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecordingPause: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/recording-pauset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecordingPauseApi - functional programming interface
 * @export
 */
export const RecordingPauseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecordingPauseApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Pause recording Map1058
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecordingPause(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecordingPause(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RecordingPauseApi - factory interface
 * @export
 */
export const RecordingPauseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecordingPauseApiFp(configuration)
    return {
        /**
         * 
         * @summary Pause recording Map1058
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecordingPause(options?: any): AxiosPromise<void> {
            return localVarFp.getRecordingPause(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecordingPauseApi - object-oriented interface
 * @export
 * @class RecordingPauseApi
 * @extends {BaseAPI}
 */
export class RecordingPauseApi extends BaseAPI {
    /**
     * 
     * @summary Pause recording Map1058
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecordingPauseApi
     */
    public getRecordingPause(options?: AxiosRequestConfig) {
        return RecordingPauseApiFp(this.configuration).getRecordingPause(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * RecordingStartApi - axios parameter creator
 * @export
 */
export const RecordingStartApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Start recording Map1058
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecordingStart: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/recording-start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecordingStartApi - functional programming interface
 * @export
 */
export const RecordingStartApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecordingStartApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Start recording Map1058
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecordingStart(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecordingStart(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RecordingStartApi - factory interface
 * @export
 */
export const RecordingStartApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecordingStartApiFp(configuration)
    return {
        /**
         * 
         * @summary Start recording Map1058
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecordingStart(options?: any): AxiosPromise<void> {
            return localVarFp.getRecordingStart(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecordingStartApi - object-oriented interface
 * @export
 * @class RecordingStartApi
 * @extends {BaseAPI}
 */
export class RecordingStartApi extends BaseAPI {
    /**
     * 
     * @summary Start recording Map1058
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecordingStartApi
     */
    public getRecordingStart(options?: AxiosRequestConfig) {
        return RecordingStartApiFp(this.configuration).getRecordingStart(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * TrialsApi - axios parameter creator
 * @export
 */
export const TrialsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * create a trial result containing a set of a subject info and rating results
         * @summary create a trial result
         * @param {PostTrialsRequest} [postTrialsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTrials: async (postTrialsRequest?: PostTrialsRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/trials`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postTrialsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TrialsApi - functional programming interface
 * @export
 */
export const TrialsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TrialsApiAxiosParamCreator(configuration)
    return {
        /**
         * create a trial result containing a set of a subject info and rating results
         * @summary create a trial result
         * @param {PostTrialsRequest} [postTrialsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postTrials(postTrialsRequest?: PostTrialsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postTrials(postTrialsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TrialsApi - factory interface
 * @export
 */
export const TrialsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TrialsApiFp(configuration)
    return {
        /**
         * create a trial result containing a set of a subject info and rating results
         * @summary create a trial result
         * @param {PostTrialsRequest} [postTrialsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postTrials(postTrialsRequest?: PostTrialsRequest, options?: any): AxiosPromise<void> {
            return localVarFp.postTrials(postTrialsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TrialsApi - object-oriented interface
 * @export
 * @class TrialsApi
 * @extends {BaseAPI}
 */
export class TrialsApi extends BaseAPI {
    /**
     * create a trial result containing a set of a subject info and rating results
     * @summary create a trial result
     * @param {PostTrialsRequest} [postTrialsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrialsApi
     */
    public postTrials(postTrialsRequest?: PostTrialsRequest, options?: AxiosRequestConfig) {
        return TrialsApiFp(this.configuration).postTrials(postTrialsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


