CREATE TABLE IF NOT EXISTS trials(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    location VARCHAR(64),
    platform VARCHAR(64),
    pre_started_at DATETIME NOT NULL,
    started_at DATETIME NOT NULL,
    ended_at DATETIME NOT NULL,
    rating_second_by_media INT UNSIGNED,
    number_of_medias INT UNSIGNED
)DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- trialsとsubjectsの関係は1対1
CREATE TABLE IF NOT EXISTS subjects(
    trial_id INT UNSIGNED PRIMARY KEY,
    age INT UNSIGNED,
    gender VARCHAR(64),
    handedness VARCHAR(64) ,
    vision VARCHAR(64),
    vision_aid VARCHAR(64),
    education VARCHAR(64),
    alcohol_consumption VARCHAR(64),
    coffee_consumption VARCHAR(64),
    tea_consumption VARCHAR(64),
    tobacco_consumption VARCHAR(64),
    drug_consumption VARCHAR(64),
    syndroms VARCHAR(64),
    hours_of_sleep_last_night FLOAT,
    normal_hours_of_sleep FLOAT,
    level_of_alertness VARCHAR(64),
    head_circumference FLOAT,
    distance_nasion_inion FLOAT,
    distance_left_right_jaw_hinge FLOAT,
    FOREIGN KEY (trial_id) REFERENCES trials(id) ON DELETE CASCADE ON UPDATE CASCADE
)DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- trialsとsignalsの関係は1対1
CREATE TABLE IF NOT EXISTS signals(
    trial_id INT UNSIGNED PRIMARY KEY,
    trend_range TEXT NOT NULL,
    channel_types VARCHAR(128) NOT NULL,
    calibration VARCHAR(128) NOT NULL,
    analyzed_signal_filename VARCHAR(128) NOT NULL,
    raw_signal_filename VARCHAR(64) NOT NULL,
    FOREIGN KEY (trial_id) REFERENCES trials(id) ON DELETE CASCADE ON UPDATE CASCADE
)DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ratingとimagesの関係は1対1
CREATE TABLE IF NOT EXISTS images(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    dataset VARCHAR(64),
    filename VARCHAR(64) NOT NULL
)DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ratingとimagesの関係は1対1
CREATE TABLE IF NOT EXISTS movies(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    dataset VARCHAR(64),
    filename VARCHAR(64) NOT NULL
)DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- trialsとratingの関係は1対多
CREATE TABLE IF NOT EXISTS rating(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    valence FLOAT NOT NULL,
    arousal FLOAT NOT NULL,
    liking FLOAT,
    dominance FLOAT,
    famility FLOAT,
    trial_id INT UNSIGNED NOT NULL,
    image_id INT UNSIGNED,
    movie_id INT UNSIGNED,
    FOREIGN KEY (trial_id) REFERENCES trials(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE ON UPDATE CASCADE
)DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO images (dataset, filename)
VALUES 
('OASIS', 'Acorns 1.jpg'),
('OASIS', 'Astronaut 1.jpg'),
('OASIS', 'Bark 3.jpg'),
('OASIS', 'Beach 1.jpg'),
('OASIS', 'Beach 7.jpg'),
('OASIS', 'Bird 1.jpg'),
('OASIS', 'Bloody knife 1.jpg'),
('OASIS', 'Bored pose 2.jpg'),
('OASIS', 'Bored pose 3.jpg'),
('OASIS', 'Boxing 2.jpg'),
('OASIS', 'Car crash 1.jpg'),
('OASIS', 'Cardboard 3.jpg'),
('OASIS', 'Cat 5.jpg'),
('OASIS', 'Clean 1.jpg'),
('OASIS', 'Couple 4.jpg'),
('OASIS', 'Cups 3.jpg'),
('OASIS', 'Destruction 10.jpg'),
('OASIS', 'Destruction 2.jpg'),
('OASIS', 'Destruction 3.jpg'),
('OASIS', 'Dirt 5.jpg'),
('OASIS', 'Dog 12.jpg'),
('OASIS', 'Dog 18.jpg'),
('OASIS', 'Dog 19.jpg'),
('OASIS', 'Dog 2.jpg'),
('OASIS', 'Dog 5.jpg'),
('OASIS', 'Dog 6.jpg'),
('OASIS', 'Dog attack 1.jpg'),
('OASIS', 'Dog attack 3.jpg'),
('OASIS', 'Eating 3.jpg'),
('OASIS', 'Elephant 1.jpg'),
('OASIS', 'Explosion 2.jpg'),
('OASIS', 'Explosion 4.jpg'),
('OASIS', 'Father 1.jpg'),
('OASIS', 'Feces 1.jpg'),
('OASIS', 'Feces 2.jpg'),
('OASIS', 'Ferret 1.jpg'),
('OASIS', 'Fire 7.jpg'),
('OASIS', 'Fire 9.jpg'),
('OASIS', 'Fireworks 1.jpg'),
('OASIS', 'Fireworks 3.jpg'),
('OASIS', 'Fireworks 7.jpg'),
('OASIS', 'Flowers 6.jpg'),
('OASIS', 'Food 3.jpg'),
('OASIS', 'Frustrated pose 1.jpg'),
('OASIS', 'Frustrated pose 3.jpg'),
('OASIS', 'Frustrated pose 7.jpg'),
('OASIS', 'Galaxy 8.jpg'),
('OASIS', 'Garbage dump 1.jpg'),
('OASIS', 'Garbage dump 2.jpg'),
('OASIS', 'Garbage dump 3.jpg'),
('OASIS', 'Garbage dump 4.jpg'),
('OASIS', 'Garbage dump 5.jpg'),
('OASIS', 'Garbage dump 6.jpg'),
('OASIS', 'Garbage dump 7.jpg'),
('OASIS', 'Garbage dump 8.jpg'),
('OASIS', 'Grass 1.jpg'),
('OASIS', 'Grass 3.jpg'),
('OASIS', 'Grass 4.jpg'),
('OASIS', 'Grass 5.jpg'),
('OASIS', 'Grass 7.jpg'),
('OASIS', 'Hallway 1.jpg'),
('OASIS', 'Hangover 1.jpg'),
('OASIS', 'Happy face 1.jpg'),
('OASIS', 'Intensity 1.jpg'),
('OASIS', 'Jail 2.jpg'),
('OASIS', 'Jail 4.jpg'),
('OASIS', 'KKK rally 2.jpg'),
('OASIS', 'Lake 12.jpg'),
('OASIS', 'Lake 14.jpg'),
('OASIS', 'Lake 15.jpg'),
('OASIS', 'Lake 16.jpg'),
('OASIS', 'Miserable pose 2.jpg'),
('OASIS', 'Mother 6.jpg'),
('OASIS', 'Mother 7.jpg'),
('OASIS', 'Neutral face 2.jpg'),
('OASIS', 'Opossum 1.jpg'),
('OASIS', 'Ornament 1.jpg'),
('OASIS', 'Paper 3.jpg'),
('OASIS', 'Parachuting 3.jpg'),
('OASIS', 'Penguins 2.jpg'),
('OASIS', 'Pinecone 1.jpg'),
('OASIS', 'Pinecone 3.jpg'),
('OASIS', 'Present 2.jpg'),
('OASIS', 'Prison 2.jpg'),
('OASIS', 'Pumpkin 1.jpg'),
('OASIS', 'Rafting 5.jpg'),
('OASIS', 'Rainbow 2.jpg'),
('OASIS', 'Rocks 1.jpg'),
('OASIS', 'Rocks 4.jpg'),
('OASIS', 'Roofing 4.jpg'),
('OASIS', 'Scared face 3.jpg'),
('OASIS', 'Scary face 1.jpg'),
('OASIS', 'School 6.jpg'),
('OASIS', 'Shark 4.jpg'),
('OASIS', 'Shooting 1.jpg'),
('OASIS', 'Shot 1.jpg'),
('OASIS', 'Shot 2.jpg'),
('OASIS', 'Shot 3.jpg'),
('OASIS', 'Sidewalk 6.jpg'),
('OASIS', 'Skydiving 3.jpg'),
('OASIS', 'Skydiving 5.jpg'),
('OASIS', 'Snake 1.jpg'),
('OASIS', 'Snake 2.jpg'),
('OASIS', 'Snake 6.jpg'),
('OASIS', 'Snow 1.jpg'),
('OASIS', 'Snow 2.jpg'),
('OASIS', 'Statue 1.jpg'),
('OASIS', 'Sunset 4.jpg'),
('OASIS', 'Surgery 1.jpg'),
('OASIS', 'Thunderstorm 3.jpg'),
('OASIS', 'Toilet 4.jpg'),
('OASIS', 'Tornado 1.jpg'),
('OASIS', 'War 1.jpg'),
('OASIS', 'War 6.jpg'),
('OASIS', 'Wedding 12.jpg'),
('OASIS', 'Wedding 4.jpg'),
('OASIS', 'Windmill 1.jpg'),
('OASIS', 'Wolf 2.jpg'),
('OASIS', 'Yarn 1.jpg'),
('OASIS', 'Yarn 3.jpg');
