/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TargetsInner struct {

	Type string `json:"type,omitempty"`

	Ids []string `json:"ids,omitempty"`
}

