/*
 * MERS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Image struct {

	MediaId int32 `json:"media_id,omitempty"`

	Type string `json:"type,omitempty"`

	Filename string `json:"filename,omitempty"`

	RatingTimes int64 `json:"rating_times,omitempty"`
}

